### PR TITLE
Improve readabiliy of main text

### LINKED ISSUE #98: Change Body color to #000000 for readability
## Describe the bug
The color of the text is dark grey.
Due to the fact that the font-weight is also 200, that's not optimal for readability.

## To Reproduce
Visit the site and look at the readability of the text on for instance a blog post

## Expected behavior
Have a bigger contrastbetween text and background

## Screenshots
image

After change to #000000

image

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
Changed body color to #000000
#98

## Related to Issue
Fixes #98 

## Description
I changed 

$font-color: #4a4a4a !default;
to
$font-color: #000000 !default;

## How Has This Been Tested?
On my local machine and by editing the CSS in the browser for the live site

## Screenshots (if appropriate):
See issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by parasdaryanani** [comment]
I would recommend using #1A1A1A instead of #000, keeping in mind UX and accessibility requirements.

Here are some references:
- https://ianstormtaylor.com/design-tip-never-use-black/

- https://uxdesign.cc/designers-should-avoid-pure-black-typography-but-which-dark-gray-should-we-use-2d7faa07083a

- https://graphicdesign.stackexchange.com/questions/50800/what-is-the-purpose-of-using-a-very-dark-color-for-text-instead-of-a-pure-black

**Comment by Timo-Breumelhof** [comment]
@parasdaryanani I mostly agree, but in this case a font weight of 200 is used, hence the #99 000000

**Comment by david-poindexter** [comment]
From an accessibility perspective, with black/white it is about contrast and anything above 55% black is acceptable.  That said, I think a shade like #1a1a1a would look better and still be in an acceptable contrast range.  #000 is fine too, but @Timo-Breumelhof may have discovered a bigger problem with the 200 default weight.  Perhaps we increase the font weight (needs testing) and see how #1a1a1a looks?

@Timo-Breumelhof if you don't have time, I can probably knock this out later today or tomorrow.

To prepare for the next release and subsequent publishing to the community site, I am going to take care of a few more PRs too.

Thanks!

**Review by david-poindexter — APPROVED** [review]
Thanks for the PR @Timo-Breumelhof 🎉

**Pull request merged**
