### PR TITLE
Next Theme version will be 02.00.01 as discusses with David

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
@david-poindexter I still had 02.00.02 as the version, changed that to 02.00.01 as discussed previously

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]

**Comment by david-poindexter** [comment]
Thanks @Timo-Breumelhof - just let me know when you are ready for a release.

**Comment by Timo-Breumelhof** [comment]
@david-poindexter The Theme is on staging for testing ATM. I'll let you know when that's done

**Comment by Timo-Breumelhof** [comment]
@david-poindexter tested on staging and now installed on live, we can release 02.00.01

**Comment by david-poindexter** [comment]
@Timo-Breumelhof the release is [HERE](https://github.com/DNNCommunity/DNNCommunityTheme/releases/tag/v2.0.1).  You can edit the release, upload the theme install package, and save.

In the future, I recommend a few small tweaks to the workflow.

1. Use the install package from latest `develop` branch or pull request build (ideally this should be automated using GitHub Actions) to test locally and/or on "staging". 
2. If good, release on GitHub and upload the install package to the new release.
3. Use the install package from the new release to deploy to "production".

Following this, or a similar workflow, will ensure no manual file manipulation occurs on "staging" or "production".  If manual file manipulation occurs but isn't accounted for in the GitHub source code and/or build process to generate the theme, then essentially problems with ongoing maintenance will occur (especially if it is someone else needed to do said maintenance).

Thanks for all the great work!

**Comment by Timo-Breumelhof** [comment]
Package uploaded

**Comment by david-poindexter** [comment]
Great - thanks @Timo-Breumelhof

**Pull request merged**
