### PR TITLE
Theme version 2023 Beta

### LINKED ISSUE #136: Theme version 2024
## Is your feature request related to a problem?
**Please describe.**
Create a new Theme based on the new design

## Describe the solution you'd like
A new Theme

## Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by Timo-Breumelhof**
## Related to Issue
Fixes #136

## Description
A complete new beta version of the 2023 Theme

## How Has This Been Tested?
Locally on a copy of the DNN Community site

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by valadas — CHANGES_REQUESTED** [review]
I really don't like having this with waay more files that don't comes from npm, it will be very hard to maintain. Why was it done this way ? Happy to help but I can't possibly review 42000 lines of code...

**Review by WillStrohl — APPROVED** [review]
Looks good.  I reviewed here in GitHub the best I could, and also checked out the PR locally, and nothing stood out as a major issue, but we'll need to test still, of course.

**Comment by WillStrohl** [comment]
Oh, I guess that's a good question for @Timo-Breumelhof

**Comment by Timo-Breumelhof** [comment]
Right I could have gotten Fontawsome and Bootstrap from NPM too, but not much more I think.

**Comment by david-poindexter** [comment]
Sorry for the late response here (been super hectic).  It appears the PR has been closed.  Can you re-open it Timo so we can just get it merged as an initial commit of the new theme?  We can work on improvements later.

**Pull request closed without merging**
